allowBuilds:
  better-sqlite3: true
  esbuild: true
  sharp: true
minimumReleaseAgeExclude:
  - "@astrojs/markdown-satteri@0.3.1"
  - "@astrojs/node@11.1.2"
  - "@astrojs/react@6.0.2"
  - "@emdash-cms/admin@0.33.0"
  - "@emdash-cms/auth@0.33.0"
  - "@emdash-cms/blocks@0.33.0"
  - "@emdash-cms/gutenberg-to-portable-text@0.33.0"
  - astro@7.2.2
  - emdash@0.33.0
onlyBuiltDependencies:
  - esbuild
  - sharp
  - better-sqlite3
